# Matrix Math and NumPy Refresher

## Data dimensions
- Scalars
  - Zero dimension
- Vectors
  - One dimension: length
  - Row vectors
  - Column vectors
- Matrix
  - Two dimensions: rows and columns
- Tensors
  - N dimensions

## NumPy
- Provide fast alternatives to math operations in Python.
- Work efficiently with groups of numbers.

In [1]:
import numpy as np

## `ndarray`
- Represent any data types: scalars, vectors, matrics, or tensors.
- Data types: signed or unsigned. For example: `uint8`, `int16`.
- Every item in the array must have the same type.

In [2]:
s = np.array(5)
print(s.shape)
# zero dimension: ()

x = s + 3
print(x)
# 8

()
8


## Vectors

In [3]:

v = np.array([1, 2, 3])
print(v.shape)
# one dimension: (3,)

print(v[1])
# 2

print(v[1:])
# [2, 3]

(3,)
2
[2 3]


## Matrices

In [4]:
m = np.array([
  [1, 2, 3],
  [4, 5, 6],
  [7, 8, 9],
])
print(m)
# [[1 2 3]
#  [4 5 6]
#  [7 8 9]]

print(m.shape)
# (3, 3)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)


## Tensors

In [5]:
t = np.array([[[[1],[2]],[[3],[4]],[[5],[6]]],[[[7],[8]],\
    [[9],[10]],[[11],[12]]],[[[13],[14]],[[15],[16]],[[17],[17]]]])
print(t.shape)
# (3, 3, 2, 1)

(3, 3, 2, 1)


## Changing shapes

In [6]:
# vector
v = np.array([1, 2, 3, 4])
print(v.shape)
# (4,)

# reshape to 1 x 4 matrix
x = v.reshape(1, 4)
print(x)
# [[1 2 3 4]]
print(x.shape)
# (1, 4)

# look for all the items of v
# and add a new dimension per row
x = v[None, :]
print(x)
# [[1 2 3 4]]
print(x.shape)
# (1, 4)

# reshape to 4 x 1 matrix
y = v.reshape(4, 1)
print(y)
# [[1]
#  [2]
#  [3]
#  [4]]
print(y.shape)
# (4, 1)

# look for all the items of v
# and add a new dimension per column
y = v[:, None]
print(y)
# [[1]
#  [2]
#  [3]
#  [4]]
print(y.shape)
# (4, 1)

(4,)
[[1 2 3 4]]
(1, 4)
[[1 2 3 4]]
(1, 4)
[[1]
 [2]
 [3]
 [4]]
(4, 1)
[[1]
 [2]
 [3]
 [4]]
(4, 1)


## Element-wise matrix operations
- Treat items in the matrix individually and perform the same operation on each one.
- Operations between a scalar and a matrix.
- Operations between two matrices.
  - They must have the same shape.

In [7]:
# scalar operations
values = np.array([1, 2, 3])
values += 5
print(values)
# [6 7 8]


[6 7 8]


In [8]:
# matrix operations

a = np.array([[1,3],[5,7]])
print(a)
# ([[1, 3],
#   [5, 7]])

b = np.array([[2,4],[6,8]])
print(b)
# ([[2, 4],
#   [6, 8]])

print(a + b)
# ([[ 3,  7],
#   [11, 15]])

[[1 3]
 [5 7]]
[[2 4]
 [6 8]]
[[ 3  7]
 [11 15]]


## Data representation

- Row representation
  - Each row represents one entity.
  - Each column represents one feature.

| Person | Height | Weight | Age |
| ---- | ---- | ---- | ---- |
| 1 | 175 | 75 | 24 |
| 2 | 203 | 102 | 31 |
| 3 | 217 | 94 | 39 |

- Column representation
  - Each column represents one entity.
  - Each row represents one feature.

| Feature | Person 1 | Person 2 | Person 3 |
| ---- | ---- | --- | ---- |
| Height | 175 | 203 | 217 |
| Weight | 75 | 102 | 94 |
| Age | 24 | 31 | 39 |

## Matrix product
- Take a series of dot product between every row in the left matrix and every column in the right matrix.
- Dot product
  - Algebraically, the dot product is the sum of the products of the corresponding entries of the two sequences of numbers.
  - Geometrically, it is the product of the Euclidean magnitudes of the two vectors and the cosine of the angle between them.
- The number of columns in the left matrix must equal the number of rows in the right matrix.
- `(x, y) x (y, z) => (x, z)`
- `np.dot` is equivalent to `np.matmul` only if both matrices are 2D. Do not use `np.dot` for matrix multiplication.
- Always multiple a row matrix with a column matrix.
  - Each dot production combines differrent features from each data entity.
  - E.g. Combine height, weight, and age from person 1.

In [9]:
a = np.array([[1,2,3,4],[5,6,7,8]])
print(a.shape)
# (2, 4)

b = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
print(b.shape)
# (4, 3)

c = np.matmul(a, b)
print(c.shape)
# (2, 3)

(2, 4)
(4, 3)
(2, 3)


## Matrix transpose

- When multiplying two row matrices:
  - Transpose the second matrix (which becomes a column matrix).
    - The result is a row matrix.
    - Each row is the combined features (with different apporaches) about one entity.
  - Transpose the first matrix (which becomes a column matrix) and swap the order.
    - The result is a column matrix.
    - Each column is the combined features (with different approaches) about one entity.
  - The answers of the two solutions are transposes of each other.
- When multiplying two column matrices:
  - The above transposing operations will not work.
  - If multiplying the first with the transposed second matrix:
    - Each dot production combines the same feature from different entities, rather than combining features for each entity (which is probably intended).
    - E.g. combine height from person 1 with height from person 2.

In [10]:
# row data
# one row per entity with four features each
inputs = np.array([ \
  [-0.27,  0.45,  0.64, 0.31], \
  [1.04, 2.27, -0.8, -1.0]])

# row data
# three different ways of combining the four features
weights = np.array([ \
  [0.02, 0.001, -0.03, 0.036], \
  [0.04, -0.003, 0.025, 0.009], \
  [0.012, -0.045, 0.28, -0.067]])

# first approach
print(np.matmul(inputs, weights.T))
# row data: each row contains the three combined data for one entity
# [[-0.01299  0.00664  0.13494]
#  [ 0.01107  0.00579 -0.24667]]

# second approach
print(np.matmul(weights, inputs.T))
# column data: each column contains the three combined data for one entity
# [[-0.01299  0.01107]
#  [ 0.00664  0.00579]
#  [ 0.13494 -0.24667]]

[[-0.01299  0.00664  0.13494]
 [ 0.01107  0.00579 -0.24667]]
[[-0.01299  0.01107]
 [ 0.00664  0.00579]
 [ 0.13494 -0.24667]]


- Transposed matrix share the same underlying data with the original matrix.
  - `numpy` simply changes the way it indexes the original matrix.

In [11]:
m = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print(m.shape)
# (3, 4)

m_t = m.T
print(m_t.shape)
# (4, 3)

# modify one matrix will also modify the other
m_t[3][1] = 200
print(m_t)
# array([[ 1,   5, 9],
#        [ 2,   6, 10],
#        [ 3,   7, 11],
#        [ 4, 200, 12]])

print(m)
# array([[ 1,  2,  3,   4],
#        [ 5,  6,  7, 200],
#        [ 9, 10, 11,  12]])


(3, 4)
(4, 3)
[[  1   5   9]
 [  2   6  10]
 [  3   7  11]
 [  4 200  12]]
[[  1   2   3   4]
 [  5   6   7 200]
 [  9  10  11  12]]


## Quiz

In [12]:
# Use the numpy library
import numpy as np


def prepare_inputs(inputs):
    # TODO: create a 2-dimensional ndarray from the given 1-dimensional list;
    #       assign it to input_array
    input_array = np.array([inputs])
    
    # TODO: find the minimum value in input_array and subtract that
    #       value from all the elements of input_array. Store the
    #       result in inputs_minus_min
    inputs_minus_min = input_array - np.min(inputs)

    # TODO: find the maximum value in inputs_minus_min and divide
    #       all of the values in inputs_minus_min by the maximum value.
    #       Store the results in inputs_div_max.
    inputs_div_max = inputs_minus_min / np.max(inputs_minus_min)

    # return the three arrays we've created
    return input_array, inputs_minus_min, inputs_div_max
    

def multiply_inputs(m1, m2):
    # TODO: Check the shapes of the matrices m1 and m2. 
    #       m1 and m2 will be ndarray objects.
    #
    #       Return False if the shapes cannot be used for matrix
    #       multiplication. You may not use a transpose
    
    # TODO: If you have not returned False, then calculate the matrix product
    #       of m1 and m2 and return it. Do not use a transpose,
    #       but you swap their order if necessary

    if m1.shape[1] == m2.shape[0]:
        return np.matmul(m1, m2)
    elif m2.shape[1] == m1.shape[0]:
        return np.matmul(m2, m1)
    else:
        return False


def find_mean(values):
    # TODO: Return the average of the values in the given Python list
    return np.mean(values)


input_array, inputs_minus_min, inputs_div_max = prepare_inputs([-1,2,7])
print("Input as Array: {}".format(input_array))
print("Input minus min: {}".format(inputs_minus_min))
print("Input  Array: {}".format(inputs_div_max))

print("Multiply 1:\n{}".format(multiply_inputs(np.array([[1,2,3],[4,5,6]]), np.array([[1],[2],[3],[4]]))))
print("Multiply 2:\n{}".format(multiply_inputs(np.array([[1,2,3],[4,5,6]]), np.array([[1],[2],[3]]))))
print("Multiply 3:\n{}".format(multiply_inputs(np.array([[1,2,3],[4,5,6]]), np.array([[1,2]]))))

print("Mean == {}".format(find_mean([1,3,4])))

Input as Array: [[-1  2  7]]
Input minus min: [[0 3 8]]
Input  Array: [[0.    0.375 1.   ]]
Multiply 1:
False
Multiply 2:
[[14]
 [32]]
Multiply 3:
[[ 9 12 15]]
Mean == 2.6666666666666665
